### ISSUE TITLE
Many parameters of imported Sheet return null.

### ISSUE THREAD

**Issue by riseio** [smartsheet-platform/smartsheet-java-sdk#56]
After attempting to obtain one of my sheets so that I can display the data many of the Sheet variables are null.

![screen shot 2017-01-20 at 14 45 25](https://cloud.githubusercontent.com/assets/5205526/22134972/41a57fa8-df1f-11e6-8890-39bd924defbe.png)

**Comment by seweil** [comment]
Since you didn't explain how you are obtaining this Sheet object, I can only give you general ideas.
- The first two parameters to `SheetResources.getSheet` specify which details to return.
- Many of the properties are expected to be null if not set.

See http://smartsheet-platform.github.io/smartsheet-java-sdk/ and specifically [getSheet](http://smartsheet-platform.github.io/smartsheet-java-sdk/com/smartsheet/api/SheetResources.html#getSheet-long-java.util.EnumSet-java.util.EnumSet-java.util.Set-java.util.Set-java.util.Set-java.lang.Integer-java.lang.Integer-)
